let length = 2;
let width = 4;
let area = length * width;
let perimeter = 2 * (length + width);
console.log("rectangle:");
console.log(area);
console.log(length);
let qatar = 9;
let p = 3.14;
let radius = 5;
let fullarea = radius * radius * p;
let fullperimeter = qatar * p;
console.log("circle:");
console.log(fullarea);
console.log(fullperimeter);
let therule = ((8 + 5) * 8) % 1;
let sides1 = 7;
let sides2 = 8;
let sides3 = 10;
let sides4 = 12;
let dark = therule;
let red = sides1 + sides2 + sides3 + sides4;
console.log("trapezoid:");
console.log(dark);
console.log(red);
