let length = 2;
let width = 4;
let area = length * width;
let perimeter = 2 * (length + width);
console.log("rectangle:");
console.log(area);
console.log(length);

let qatar = 9;
let p = 3.14;
let radius = 5;
let fullarea = radius * radius * p;
let fullperimeter = qatar * p;
console.log("circle:");
console.log(fullarea);
console.log(fullperimeter);

let therule1 = 8;
let therule2 = 5;
let therule3 = 4;
let therule4 = 2;
let sides1 = 7;
let sides2 = 8;
let sides3 = 10;
let sides4 = 12;
let carea = ((therule1 + therule2) * therule3) / therule4;
let cperimeter = sides1 + sides2 + sides3 + sides4;
console.log("trapezoid:");
console.log(carea);
console.log(cperimeter);
