let length = 2;
let width = 4;
let area = length * width;
let perimeter = 2 * (length + width);
console.log("rectangle:");
console.log(area);
console.log(length);
let qatar = 9;
let p = 3.14;
let radius = 5;
let fullarea = radius * radius * p;
let fullperimeter = qatar * p;
console.log("circle:");
console.log(fullarea);
console.log(fullperimeter);
